apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-webkins
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      wk: web
  template:
    metadata:
      labels:
        wk: web
    spec:
      containers:
        - name: webkins-site
          image: webkins:1.0
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: wk-entry
  namespace: default
spec:
  type: NodePort
  selector:
    wk: web
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001

