---
networks:
  infrastructure: {}
  frontend: {}
services:
  webkins:
    image: webkins-react:1.0
    container_name: webkins
    build:
      context: ../../
      dockerfile: build/docker/service-react.Dockerfile
    ports:
      - "8080:8080/tcp"
    networks:
      infrastructure: {}
      frontend:
        aliases:
          - bodkins
